home-page setup
ihor-kropyvnyi-moc/ZipifyFrontendOnboarding pull request #2
Opened 2022-06-27 15:50 UTC by ihor-kropyvnyi-moc

2022-06-29 06:31 UTC, misha-kolosov-moc requested changes

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/App.vue
> +        </header>
это выглядит как-то что лучше сделать отдельным компонентом. Ты вроде изначально выносил хедер компонентом

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/App.vue
> +components: {  }
тут также должно быть поле name с названием компонента. В данном случае `name: 'App'`

если ты не подключаешь сторонние компоненты, то тебе это поле `components` не нужно

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/core/UI/UiButton.vue
>          clickUiButton() {
метод достаточно просто назвать `click`. Добавлять специфичности названиям стоит по необходимости. Например, если у тебя в компоненте есть три кнопки, тогда можно уточнить в названии метода что это за клик

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/core/UI/UiButton.vue
> +        typeButton:String,
тоже касается и пропса. Компонент и так называется Button. В названии пропса нет необходимости писать `Button`, так как и так понятно. 
Также хорошей практикой является передавать пропс обьектом с полем required, чтобы избежать возможных ошибок 

Например в твоем случае это будет выглядеть так:
```suggestion
        type: {
            type: String,
            required: true
        },
```

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageView.vue
> +    <EditorPage></EditorPage>
```suggestion
    <EditorPage />
```

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageEmptyBanners.vue
> +            console.log('1')
точно нужен `console.log`?

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageEmptyBanners.vue
> +            this.$emit('clickNewBannerEmpty');
не очень нравится название ивента(

можно задавать себе вопрос, что делает этот клик? в данном случае ивент можно назвать `create`

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageEmptyBanners.vue
> +.tt-page__tt-button--second {
`tt` два раза повторяется.. не совсем корректное название классика. Что-то из этого можно вынести в `UIButton`?

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +    <HomePageWithBanners @clickNewBanner="createNewBanner" v-else></HomePageWithBanners>
и по сути переименовав свой ивент, оба компонента будут слушать событие `create` и логически становится понятнее что делает этот ивент  

```suggestion
    <HomePageEmptyBanner @create="createNewBanner" v-if="isShowBlock" />

    <HomePageWithBanners @create="createNewBanner" v-else />

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
>      }
такое лучше удалять)

2022-06-29 06:31 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +                  @click="createNewBanner">Create new banner</UiButton>
если ты начал делать мультилайн, то уже все проперти нужно мультилайном делать
```suggestion
        <UiButton 
            class="tt-page__tt-button tt-page__tt-button--first"
            :typeButton="'button'"
            @click="createNewBanner">
                 Create new banner
             </UiButton>
```

2022-06-29 06:49 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +                  @click="createNewBanner">Create new banner</UiButton>
понял, щас всё исправлю

2022-06-29 08:02 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/App.vue
> +        </header>
Да, выносил когда то) исправил

2022-06-29 08:03 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/App.vue
> +components: {  }
иправил

2022-06-29 08:09 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/core/UI/UiButton.vue
>          clickUiButton() {
Я пробовал ставить название click, но когда я передавал emit родителю начали дублироваться ивенты, поэтому пришлось изменить название

2022-06-29 08:10 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/core/UI/UiButton.vue
> +        typeButton:String,
спасибо, учту

2022-06-29 08:40 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageEmptyBanners.vue
> +            this.$emit('clickNewBannerEmpty');
хорошо

2022-06-29 08:48 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageEmptyBanners.vue
> +.tt-page__tt-button--second {
исправил

2022-06-29 08:53 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +    <HomePageWithBanners @clickNewBanner="createNewBanner" v-else></HomePageWithBanners>
исправил

2022-06-29 08:53 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
>      }
хорошо))

2022-06-29 08:54 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageView.vue
> +    <EditorPage></EditorPage>
исправил

2022-06-29 14:17 UTC, misha-kolosov-moc requested changes

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/Button.vue
> +            <slot/>
```suggestion
    <button
        class="tt-button"
        :type="type"
        @click="onClick"
    >
            <slot/>
```

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        <div class="container-loader__loader">
не нравится название класса(

1 - `container` ? если тут и должно быть это слово, то точно не в начале, так как у тебя это контейнер лоадера, а не лоадер контейнера

2 - префикс `tt`

3 - `loader__loader` - не очень валидное название

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +    <div class="container-loader">
не уверен что слово `container` тут целесообразно

это бейс компонент лоадера - от этого нужно и отталкиваться

Например рутовый класс может быть `tt-loader`

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        background: #fc3747;
во многих местах у тебя цвета записаны в таком кейсе, а в других капсом.

Нужно привести к одному виду:
```suggestion
        background: #FC3747;
```

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        background: #fc3747;
background проперти включает в себя очень много css проперти. По сути у тебя билдится такой css - https://tppr.me/vRDln

Но тебе тут только цвет нужно указать

```suggestion
        background-color: #FC3747;
```

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +    .container-loader .container-loader__loader .loader__moving-indicator {
у тебя тут везде большая специфичность. Это специально было сделано?

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageBanner.vue
> +        class="tt-home-page-banner">
и поправь тут мультилайн и ниже

P.S. но если используется только один атрибут, мультилайн можно не использовать)
```suggestion
    <div
        class="tt-home-page-banner"
    >
```

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageBanner.vue
> +            :type="'button'">
статические пропы можно передавать без динамики

```suggestion
            type="button"
        >
```

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageBanner.vue
> +            id: '',
зачем тут эта id? не вижу ее использования

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePagePopup.vue
> +            this.axios.delete(`/api/v1/banners/`+ this.idBanner)
в компонентах нельзя описывать запросы

как раз для этого и нужен `Vuex` или `Pinia`. Это делается в экшинах

https://zipifyapps.slack.com/archives/C03KWUCT72B/p1656489323036679

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePagePopup.vue
> +    name: "HomePagePopup",
этот компонент выглядит как base.

Его можно использовать и в других местах для конфирма различных действий.

вынеси его в baseComponents и назвови, например - `Confirm`. И всю логику описывай вне таких компонентов. а просто отправляй ивен, например - `this.$emit('confirm');`

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +        },
тоже самое. Запросы выносятся в экшины. Если что, можешь пока запросы тут оставить, так как там довольно объёмная работа будет по переносу это все в стейт менеджер

2022-06-29 14:17 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +                   :idBanner="idBanner"
а зачем id баннера в попапе?

2022-06-30 06:23 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        <div class="container-loader__loader">
исправил

2022-06-30 06:36 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        background: #fc3747;
исправил

2022-06-30 06:37 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +    <div class="container-loader">
хорошо

2022-06-30 06:37 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        background: #fc3747;
исправил

2022-06-30 07:08 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +                   :idBanner="idBanner"
уже переделал

2022-06-30 07:09 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +        },
уже переделал

2022-06-30 07:09 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePagePopup.vue
> +    name: "HomePagePopup",
хорошо

2022-06-30 07:09 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePagePopup.vue
> +            this.axios.delete(`/api/v1/banners/`+ this.idBanner)
исправил

2022-06-30 07:13 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageBanner.vue
> +            id: '',
то я хотел для передачи id на удаление

2022-06-30 11:31 UTC, vladyslav-chudak-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageBanner.vue
> +            :type="'button'">
також рекомендую сінгл-атрібут елементи писати в одну строчку, і тільки мульті-атрібутні розділять так як ти написав

2022-06-30 11:31 UTC, vladyslav-chudak-moc commented on app-frontend/packs/components/baseComponents/LoaderPage.vue
> +        background: #fc3747;
змінні для кольорів)

2022-07-04 06:57 UTC, misha-kolosov-moc submitted a review, later dismissed

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/HeaderPage.vue
> +            class="tt-link tt-page__link-logo"
чисто как предложение - лучше классы писать всегда первыми, а потом остальные атрибуты. Так легче сразу понять что это за элемент и за что он отвечает)

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +        type: String,
лучше описывать пропсы объектом с указанием поля `required`. Если `required: false` - то также передавай `default` 
Примеры: 
https://tppr.me/ZdgGw
https://tppr.me/zhT0v

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +            :type="'text'"
зачем `:`? тут будет динамика?

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                 @update:model-value-wysiwyg="setInputWysiwyg"/>
подправь мультилайн

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +        this.$store.commit('banners/setInputColor', '#FFFFFF')
```suggestion
        this.$store.commit('banners/setInputColor', '#FFF')
```

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +        this.$store.commit('banners/setInputColor', '#FFFFFF')
почитай про `mapState, mapGetters, mapActions, mapMutations`

мы в проекте стучимся через эти хелперы

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +        <HomePageEmptyBanner
```suggestion
        <HomePageEmptyState
```

лучше переименовать, а то выгдяжит так, как буд-то хоум пейджа с пустым баннером

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +            fetchBanners: 'banners/fetchBanners',
название экшинов/гетеров/мутаций лучше вынести в константы

2022-07-04 06:57 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +        @confirm="isShowPopup = false"
логику обычно выносят в методы, не важно одна строка тут или нет. Так как логика может увеличиться 

```suggestion
        @confirm="closePopup"
```

2022-07-04 14:51 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/HeaderPage.vue
> +            class="tt-link tt-page__link-logo"
хорошо

2022-07-04 14:52 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +        type: String,
понял

2022-07-04 14:54 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +            :type="'text'"
без : не работает input color

2022-07-04 14:54 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                 @update:model-value-wysiwyg="setInputWysiwyg"/>
хорошо

2022-07-04 14:57 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +        <HomePageEmptyBanner
исправил

2022-07-04 15:09 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +        @confirm="isShowPopup = false"
виправив

2022-07-04 15:10 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +        this.$store.commit('banners/setInputColor', '#FFFFFF')
хорошо

2022-07-06 07:25 UTC, misha-kolosov-moc requested changes

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/Wysiwyg.vue
> +    }
это точно нужно?

```suggestion
```

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +            if (!this.v$.inputText.$invalid && (this.inputLengthWysiwyg >= MIN_LENGTH_WYSIWYG) && (this.inputLengthWysiwyg < MAX_LENGTH_WYSIWYG)) {
это лучше вынеси в компьютед типо `isInputInvalid()`

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                }
if внутри if'а лучше избегать. Например можно сделать обратное условие с `return`. 
После выноса в компьютед у тебя может получится что-то типо такого:
```suggestion
            if (this.isInputInvalid) return;
            
            if (this.idBannerChange) {
                this.changeBanner();
            } else {
                this.createBanner();
            }
```

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +        }),
мутации в компоненте лучше не вызывать. Все мутации должны быть связаны с экшенами, а уже в свою очередь, экшены дергают мутации и если нужно отправляют запрос на сервер

https://dev.to/timothyokooboh/vuex-best-practices-45dd
пункт B

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPagePreviewBanner.vue
> +        <p v-html="this.innerWysiwyg"></p>
```suggestion
        <p v-html="this.innerWysiwyg" />
```

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +            isLengthData: state => state.banners.isLengthData
не очень понятное название

лучше уже так
```suggestion
            isEmpty: state => state.banners.isEmpty
```

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +            :key="banner"
ключом по возможности передавать `id`
я думаю от бекенда приходит это поле

2022-07-06 07:25 UTC, misha-kolosov-moc commented on app-frontend/packs/store/bannersModule.js
> +export const bannersModule = {
вынеси стейт/мутации/экшини в отдельный файл

2022-07-06 07:27 UTC, misha-kolosov-moc requested changes

2022-07-06 07:27 UTC, misha-kolosov-moc commented on .eslintrc.js
> +    }
добавь какие-то рулы для еслинта

2022-07-07 10:00 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/Wysiwyg.vue
> +    }
исправил

2022-07-07 10:06 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageView.vue
> +            isLengthData: state => state.banners.isLengthData
добре

2022-07-07 10:07 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/homePage/HomePageWithBanners.vue
> +            :key="banner"
Исправил

2022-07-07 16:19 UTC, ihor-kropyvnyi-moc commented on .eslintrc.js
> +    }
хорошо

2022-07-07 16:19 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/store/bannersModule.js
> +export const bannersModule = {
вынес

2022-07-07 16:20 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +        }),
хорошо

2022-07-07 16:20 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                }
ок

2022-07-07 16:20 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +            if (!this.v$.inputText.$invalid && (this.inputLengthWysiwyg >= MIN_LENGTH_WYSIWYG) && (this.inputLengthWysiwyg < MAX_LENGTH_WYSIWYG)) {
сделал

2022-07-08 06:28 UTC, misha-kolosov-moc requested changes

2022-07-08 06:28 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +        default: false
это работать не будет. Этим кодом ты добавил просто два новых пропса. `required`  и `default`, которые ты не используешь

2022-07-08 06:28 UTC, misha-kolosov-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +    },
что-то должно получится типа такого:

Если ты тайп всегда передаешь, то указывай значение `required: true` и `default` тогда не нужен

Если это пропс, который можно передавать, а можно и нет, то указывай `required: false` и тогда передавай `default`

```suggestion
    props: {
        modelValue: {
            type: [String, Number],
            required: true
        },
        
        type: {
            type: String,
            required: true
        }
    },
```

2022-07-08 06:28 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                v-if="this.v$.inputText.$dirty && this.v$.inputText.$invalid"
такие колбаски лучше выносить в компьютед

`this.v$.inputText.$dirty && this.v$.inputText.$invalid`

2022-07-08 06:28 UTC, misha-kolosov-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                v-if="this.v$.inputText.$dirty && ((this.inputLengthWysiwyg < 2) || (this.inputLengthWysiwyg >= 20))"
🥓🥓🥓🥓

2022-07-08 06:57 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +        default: false
понял, спасибо

2022-07-08 06:58 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/baseComponents/Input.vue
> +    },
исправил

2022-07-08 06:58 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                v-if="this.v$.inputText.$dirty && this.v$.inputText.$invalid"
вынес

2022-07-08 06:58 UTC, ihor-kropyvnyi-moc commented on app-frontend/packs/components/dashboard/editorPage/EditorPageEditForm.vue
> +                v-if="this.v$.inputText.$dirty && ((this.inputLengthWysiwyg < 2) || (this.inputLengthWysiwyg >= 20))"
исправил)))

2022-07-08 06:59 UTC, merged